# Generated by Django 5.1.4 on 2025-01-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
