# Generated by Django 5.1.4 on 2025-01-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_backend', '0002_alter_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
